# Project: CvEmu2
# Modernized Makefile for Windows / MinGW (SDL2)

# --- CONFIGURATION ---
# Adjust SDL_PATH to point to your SDL2 installation folder (containing 'include' and 'lib')
# Example: SDL_PATH = C:/SDL2
SDL_PATH = C:/SDL2

CPP      = g++
WINDRES  = windres.exe
RM       = rm -f

BIN      = CvEmu2.exe
RES      = CreatiVemu_private.res

# --- FLAG DI COMPILAZIONE ---
INCS     = -I"$(SDL_PATH)/include" -I.
CXXFLAGS = $(INCS) -w -O2 -g
CFLAGS   = $(INCS) -Dmain=SDL_main -w -O2 -g

# Linkage for SDL2 on Windows/MinGW
LIBS     = -L"$(SDL_PATH)/lib" -lmingw32 -lSDL2main -lSDL2 -lz

# --- ELENCO SORGENTI ---
OBJ  = video/tms9918.o mem/cvmemory.o cpu/cpu6502.o pia/6821pia.o \\
       video/drv9918.o main.o audio/sn76496.o font/font.o \\
       savestate/savestate.o menu/menu.o keyboard/keyboard.o $(RES)

.PHONY: all clean

all: $(BIN)

# Rule for C++ files
%.o: %.cpp
	$(CPP) -c $< -o $@ $(CXXFLAGS)

# Rule for C files (if any)
%.o: %.c
	$(CPP) -c $< -o $@ $(CFLAGS)

# Compile Windows resource file (icon)
$(RES): CreatiVemu_private.rc
	$(WINDRES) $< -o $@

# Final Link
$(BIN): $(OBJ)
	$(CPP) $(OBJ) -o $(BIN) $(LIBS)

clean:
	$(RM) $(OBJ) $(BIN)
