# Project: CvEmu2
# Makefile semplificato per Windows / MinGW

# --- CONFIGURAZIONE PATH DEV-C++ E SDL ---
DEVCPP_DIR = C:/Programmi/Dev-Cpp
SDL_DIR    = $(DEVCPP_DIR)/include/SDL

CPP     = g++.exe -D__DEBUG__
CC      = gcc.exe -D__DEBUG__
WINDRES = windres.exe
RM      = rm -f

BIN  = CvEmu2.exe
RES  = CreatiVemu_private.res

# --- FLAG DI COMPILAZIONE ---
INCS     = -I"$(DEVCPP_DIR)/include" -I"$(SDL_DIR)" -I.
CXXFLAGS = $(INCS) -w -fexpensive-optimizations -O3 -g3
CFLAGS   = $(INCS) -Dmain=SDL_main -w -fexpensive-optimizations -O3 -g3

LIBS     = -L"$(DEVCPP_DIR)/lib" -mwindows -lmingw32 -lSDLmain -lSDL -liberty -g3

# --- ELENCO SORGENTI ---
OBJ  = video/tms9918.o mem/cvmemory.o cpu/cpu6502.o pia/6821pia.o \
       video/drv9918.o main.o audio/sn76496.o font/font.o \
       savestate/savestate.o menu/menu.o keyboard/keyboard.o $(RES)

.PHONY: all clean

all: $(BIN)

# Regola generica per i file .cpp (es. main.cpp, font.cpp)
%.o: %.cpp
	$(CPP) -c $< -o $@ $(CXXFLAGS)

# Regola generica per i file .c (la maggior parte dei tuoi sorgenti)
%.o: %.c
	$(CPP) -c $< -o $@ $(CXXFLAGS)

# Regola per compilare il file delle risorse Windows (icona, info eseguibile)
$(RES): CreatiVemu_private.rc
	$(WINDRES) -i $< --input-format=rc -o $@ -O coff

# Link finale dell'eseguibile
$(BIN): $(OBJ)
	$(CPP) $(OBJ) -o $(BIN) $(LIBS)

clean:
	$(RM) $(OBJ) $(BIN)
